version: '2.2'
services:
  db:
    image: postgres:13
    restart: "always"
    environment:
      - POSTGRES_USER=invenio
      - POSTGRES_PASSWORD=invenio
      - POSTGRES_DB=invenio
    ports:
      - "5432:5432"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    restart: "always"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"

  cache:
    image: redis:6
    restart: "always"
    ports:
      - "6379:6379"

  mq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"

  web-api:
    image: inveniosoftware/invenio-app-rdm:latest
    restart: "always"
    environment:
      - INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://invenio:invenio@db/invenio
      - INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/
      - INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/
      - INVENIO_CACHE_TYPE=redis
      - INVENIO_CACHE_REDIS_URL=redis://cache:6379/0
      - INVENIO_SEARCH_ELASTIC_HOSTS=["es:9200"]
    volumes:
      - ./invenio.cfg:/opt/invenio/var/instance/invenio.cfg
    ports:
      - "5000:5000"
    depends_on:
      - db
      - es
      - cache
      - mq